/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Marketplace__factory } from "./Marketplace__factory";
export { Pokemon__factory } from "./Pokemon__factory";
